apiVersion: v1
kind: Secret
metadata:
  name: ipv64-api-key
  namespace: cert-manager
type: Opaque
stringData:
  IPV64_API_KEY: ENC[AES256_GCM,data:3iwzGWxj8v6pMr7ZfIdpgMGvfgPb4gE7s33hZ8lgXKE=,iv:GYy+zn9X2Efl6IwMp4dDTHxVjyCzoheYQVBQqGDrZB8=,tag:VTUm6DiGHcaBDydsnvYc8Q==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaDVyNzNWaWJNZzZMY3hB
        STFwWTlTMVFqbW1LLytXUHJvZDRiMGpOTGdzCjdPU0psMWhoYjZiSVdwVERmVDl2
        d0xKMUkvbTloRU5Fd2NoaFVVWVB0TGMKLS0tIFcvUkZVNmxHeVlVRWR0c21jLzBL
        bWJMMjlkMVJQTk41bHNRZEdqZmNDZEkKhcH6YT7Vl9lmmrgFXZ+4/GCeQBLPqRi0
        Ok+8p7Sv2FS98zIk/W2kKSTaAcWKra1PwlxINXgIHxCdpFAdIEElNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T09:20:39Z"
  mac: ENC[AES256_GCM,data:3WzpepxQvpxcLHV+z8NFyZiMjQNV9RaBmVmFH2KDs/guPy9RXGmDZRaV2TV6GUxaENOKDneNwlW2zZJBW5XkHA5SHfg3hJugr16Bs1nBBy32MWCWBpsi2GKmaMNdjUO6wBm3ZfFumgTu/0M27xfms6HMO/M4G6Oj1bw5YbCklis=,iv:iHugF0fWyhQG0kHpI0J6My+09c4f7c12SKewcONkxUQ=,tag:UPwAavr8B0E5lWrXvH3Qfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
