keys:
  - &age_key age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7

stores:
  yaml:
    indent: 2

creation_rules:
  # Kubernetes
  - path_regex: kubernetes/.*\.sops\.ya?ml$
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - *age_key
  # Talos
  - path_regex: talos/.*\.sops\.ya?ml$
    encrypted_regex: '^(id|secret|bootstraptoken|secretboxencryptionsecret|token|crt|key)$'
    key_groups:
      - age:
          - *age_key
