apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${PVC}
spec:
  sourcePVC: ${PVC}
  trigger:
    schedule: ${VOLSYNC_SCHEDULE:=0 3 * * *}
  rclone:
    rcloneConfig: ${VOLSYNC_RCLONE_CONFIG:=rclone-filen}
    rcloneConfigSection: ${VOLSYNC_RCLONE_CONFIG_SECTION:=filen}
    rcloneDestPath: Backups/beehive/volsync/${PVC}
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
      fsGroupChangePolicy: OnRootMismatch
