{
 "title": "Speedtest (Own)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Download / Upload",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_download_megabits_per_second",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_megabits_per_second",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Best Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(speedtest_download_megabits_per_second[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worst Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(speedtest_download_megabits_per_second[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Best Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(speedtest_upload_megabits_per_second[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worst Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(speedtest_upload_megabits_per_second[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Best Ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(speedtest_ping_latency_milliseconds[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worst Ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(speedtest_ping_latency_milliseconds[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Best Jitter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(speedtest_jitter_latency_milliseconds[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worst Jitter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(speedtest_jitter_latency_milliseconds[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping / Jitter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "Ping"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "Download Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "speedtest_download_megabits_per_second",
     "legendFormat": "asdsa"
    }
   ]
  },
  {
   "title": "Test Results",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "speedtest_download_megabits_per_second",
     "legendFormat": "__auto"
    },
    {
     "expr": "speedtest_upload_megabits_per_second",
     "legendFormat": "__auto"
    },
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}