apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  type: oci
  url: oci://ghcr.io/heathcliff26/manifests
  interval: 6h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: speedtest-exporter
      version: v1.5.0
      sourceRef:
        kind: HelmRepository
        name: speedtest-exporter
        namespace: monitoring
      interval: 6h
  valuesFrom:
    - kind: ConfigMap
      name: speedtest-exporter-helm-values
