# resources:
#   - helm.yaml
# configMapGenerator:
#   - name: speedtest-exporter-helm-values
#     files:
#       - values.yaml
# generatorOptions:
#   disableNameSuffixHash: true

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: speedtest-exporter-dashboard
    files:
      - dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
