resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: speedtest-exporter-dashboard
    files:
      - dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
