apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  labels:
    app: speedtest-exporter
spec:
  ports:
    - name: metrics
      port: 80
      targetPort: metrics
  selector:
    app: speedtest-exporter
