analytics:
  enabled: false

node:
  metadataDirPath: /var/mnt/local-storage/openebs-rawfile-meta
  storagePools:
    default:
      path: /var/mnt/local-storage/openebs-rawfile
  snapshotController:
    enabled: false # kommt aus infrastructure/crd/storage-system/external-snapshotter

# workaround für bug in helm chart
snapshotClasses: []

crds:
  enabled: false

storageClasses:
  - name: rawfile-localpv
    enabled: true
    isDefault: true
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    reclaimPolicy: Delete
    storagePool: default
    copyOnWrite: true
    freezeFs: false
