apiVersion: v1
kind: ConfigMap
metadata:
  name: webchanges-config
  labels:
    app: webchanges
data:
  urls.yaml: null
  config.yaml: ENC[AES256_GCM,data:+82LxJz6JS/T6LKIGzRJVfHdeUUsEW1IVu2UvHEOymUQkJyvyBWC078U2fjcDHHac7W/bJVjBfSI7/iniSKno4mrPNE4PcpvFHV/KpzYIr6hyg61rWImepEnRabDfcz1stZFLmQt7BM8SddWjAJ+D5DZ5KSH2rsyoIqkhbsjuA4dUVrkL+1Ajwf4KbDSk1S3J7aoE6KaTsoaccgFsVZpR5Pm3o+LjiVhGeV6hrretQIkAzl7nF8gDoeAWuJw4kOEA4gaVQDiAxZZc4EXGSV3yLCZ3AJ0WuhDyVmJSsUmSKL+5+rzsbsm2POPvz/zdHJVdL/SzpZQ+XfWZ7ZtmGEoOmeM4Z3dbB27AjmvKKSxnmT6VGzsMiKI3I4i+0GVXCHot1H4qLj2vCdyaX9A8XnklU/65iT/p/ZuxGkRBwfTHbsuJVv0PQRQ/SGQ0P/j8Yh4SE/tAoiPlWYY6U6TqpROKm93qALHGhjIyDtbBoGp7bNelAp+Kj5/yeQG4eSG7KsQbl3iUAPZLPbP6S/E+/x8zPayv+iI+F6U,iv:buS7MNK/q0iT3XrcmTnFfJWh7wYkWRd619Uo1ZV426k=,tag:cZc05kJIr07Pij+znbVHUg==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRFdZNVJJSEgwL0hKWi9N
        dEJxTnovb1BZS1psQ2JSenVKSUFDbVpBZHpFCnpiNDhoT2ViVVBlU0N3cEJoM2RZ
        cTlnaGlJWitETU0rbjRyV0xMV3k2RWsKLS0tIFdpbytMbjFxenMzZWtTUjR3T1RN
        OVo4bWpVK2U4Um9RcU93RFE0a3RUREkKma9z+pGy7tBlRZ0L3myGHfjRhasoIbXg
        98V/qImklp+vBhjfZurPTYiTVdIFczNSk+YGG+DhqTpX0nU97yE9cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T11:01:55Z"
  mac: ENC[AES256_GCM,data:Jc1UwExf0mADkXx2kvlMCX3dqBiJgKTMlg7mH912F3U6NDR2EDqlxcUZTESmdGogtpifmXyTLeDuY/fzSWm813Cg6cbTo9fvsK1GKKX/IkMl1+47qa6i75zP0bmdw+PMj2JZ2k/qe8BZ5ct39h30E+2NFWkNDBmObDrbYgLKZio=,iv:qDebWbBcqztUMq/qjxb8XYHIOXMoGy57I+7KJoNobCA=,tag:tyy6tGWs1Bt+H2FgAZlekw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
