apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ai
  labels:
    app: paperless-ngx
    name: paperless-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
