---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 24h
  values:
    controllers:
      immich-db:
        replicas: 1
        containers:
          database:
            image:
              repository: ghcr.io/immich-app/postgres
              tag: 16-vectorchord0.4.3-pgvectors0.2.0
            env:
              POSTGRES_USER: &dbUser immich
              POSTGRES_DB: &dbName immich
              POSTGRES_PASSWORD: &dbPassword Immich123!()
              POSTGRES_INITDB_ARGS: --data-checksums
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 2Gi

          redis:
            image:
              repository: docker.io/valkey/valkey
              tag: 9.1.0-alpine
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 2Gi
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - redis-cli
                      - ping
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - redis-cli
                      - ping

      immich-server:
        replicas: 1
        containers:
          server:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.0.2
            env:
              REDIS_HOSTNAME: immich-db
              DB_HOSTNAME: immich-db
              DB_USERNAME: *dbUser
              DB_DATABASE_NAME: *dbName
              DB_PASSWORD: *dbPassword
              TZ: Europe/Berlin
              IMMICH_CONFIG_FILE: /config/immich.json
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 8Gi

          machine-learning:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v3.0.2
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 2Gi

      immich-sync:
        type: cronjob
        cronjob:
          schedule: "@hourly"
        containers:
          filen-sync:
            image:
              repository: ghcr.io/kaerbr/shipyard/filen-cli
              tag: 0.0.36
            args:
              - sync
              - /external/photos:cloudToLocal:/Bilder
              - --verbose
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 8Gi
            envFrom:
              - secretRef:
                  name: filen-cli

    # 2. Service/Ingress
    service:
      server:
        controller: immich-server
        ports:
          http:
            port: 2283
      db:
        controller: immich-db
        ports:
          postgres:
            port: 5432
          redis:
            port: 6379

    ingress:
      server:
        className: traefik
        hosts:
          - host: immich.beehive.lan64.de
            paths:
              - path: /
                service:
                  identifier: server
                  port: http

    # 3. Persistence (Storage)
    persistence:
      config:
        type: configMap
        name: immich-config
        advancedMounts:
          immich-server:
            server:
              - path: /config
                readOnly: true

      # The main Immich upload folder (Internal) - Only for Server
      library:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 25Gi
        advancedMounts:
          immich-server:
            server:
              - path: /data

      # YOUR EXTERNAL LIBRARY - Only for Server (and ML if you want OCR on external files)
      external:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Gi
        advancedMounts:
          immich-server:
            server:
              - path: /external/photos
                readOnly: true
            machine-learning:
              - path: /external/photos
                readOnly: true
          immich-sync:
            filen-sync:
              - path: /external/photos

      # Postgres Data - Only for Database
      database:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          immich-db:
            database:
              - path: /var/lib/postgresql/data

      # Machine Learning Model Cache - Only for Machine Learning
      model-cache:
        type: emptyDir
        advancedMounts:
          immich-server:
            machine-learning:
              - path: /cache
