namespace: default
resources:
  - ./podinfo
  - ./paperless-ngx
  - ./miniserve
  - ./webchanges
  - ./immich
  - ./omni-tools
  # - ./local-ai
  - app-template.ocirepository.yaml
  - rclone-filen.secret.sops.yaml
