apiVersion: v1
kind: Secret
metadata:
  name: rclone-filen
stringData:
  rclone.conf: ENC[AES256_GCM,data:sx8+7XV4B+thBcPXo+RT49bwOYl7N1RdUGGciNoR6jUkH+zyQDjUozNhf47/sjv85zNGrGdiF7FEFoxsbv/UVGt0yovcjvpDAPTFwGF3xqRG7z8H+3EUxuD1aNS4jjLb9+EvHxxMMtRL8/SzkDPnN+p7Anv1vNdBxTaJOXA7bxPrmNl+42q/WQn54hJ2IERJREZH+c+xH5NvC8e2/xgmU08xQ5JJILjxeWvgEqw5eBmwqJQc+7fzGF0j9wp5AsKdoQIBwbBRYhU3HrxAYp7o5nHekOFnC5WZWwwjNdyG4LZ9dNT9CxtNgUckaN1wvg==,iv:N9ie3CRexju9ufCPTCBF43Dm7xg4ZPJVN6FfWPD2nVU=,tag:HUasJ/wFK6GvvhkAt/aY/g==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdE1EQVZ3VGdRZVI5VlZE
        NVl6OFRwMUhSUmlmSU5XVXBoUG9iUCtWZlRJCnhVYUtzL05lU0hOYlFMdzg3Tno5
        T2hjdEYxTGc0SHBDb2NyNy9KV0d5bk0KLS0tIGxnZGQxVmk2aEdwa3NQdDJIbDZR
        S3paQldwazY2TmN4bDQ3bWFkbWFLbkEK2In44L/A9w6vbsPUGMs/ifZxYC8pt+8b
        W/B4ZVdfGmRzzKXekOTVHZkah5sYJd71kr3ZLdcxkXunOqBuzhOe4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-25T11:28:27Z"
  mac: ENC[AES256_GCM,data:oNhnlXj6FSoCY+nfJZk9y89j4XMw2ck0rx4GEknz/vKZ8UD3eJ1p8TwmiGb3IWG6Nl9ZhVhXtbBiuBx33EtwKuopXiaXdAY0+LcwkHNdft68qlAKn27I1UkFpQehqwgyII3xrAuNb42mgfkBrJ4mJ0stsChCXHv6uLwsvxWjIfg=,iv:Y77JaGYIOZCvXHeY0ZRg+t1fChhrWyKLu6cDqKw6s18=,tag:8W5Yk8qRMrraVR93xiW5pw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
