apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      securityContext:
      automountServiceAccountToken: false
      containers:
        - name: ollama
          image: alpine/ollama:0.20.2
          ports:
            - containerPort: 11434
              name: http
          volumeMounts:
            - name: ollama
              mountPath: /root/.ollama
          resources:
            requests:
              cpu: 10m
              memory: 2Gi
            limits:
              memory: 12Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
