---
machine:
  install:
    disk: /dev/sda
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: true # as there is a single link only, we can match it this way
---
apiVersion: v1alpha1
kind: LinkConfig
name: net0
addresses:
  - address: 192.168.178.181/24
