# kubernetes/apps/default/paperless-ngx/backup.cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-ngx-backup
  labels:
    app: paperless-ngx
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: export
              image: ghcr.io/paperless-ngx/paperless-ngx:3.2.1
              workingDir: /usr/src/paperless/src
              command:
                - python3
                - manage.py
                - document_exporter
                - /backup
                - --zip
                - --zip-compression=lzma
                - --delete
                - --no-progress-bar
              env:
                - name: PAPERLESS_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: paperless-ngx
                      key: PAPERLESS_SECRET_KEY
              securityContext:
                runAsUser: 1000 # paperless user
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - name: data
                  mountPath: /usr/src/paperless/data
                - name: media
                  mountPath: /usr/src/paperless/media
                - name: backup
                  mountPath: /backup
          containers:
            - name: upload
              image: ghcr.io/kaerbr/shipyard/filen-cli:0.0.36
              args:
                - sync
                - /backup:localToCloud:/Backups/beehive/paperless-ngx
                - --verbose
              envFrom:
                - secretRef:
                    name: filen-cli
              volumeMounts:
                - name: backup
                  mountPath: /backup
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: paperless-ngx-data
            - name: media
              persistentVolumeClaim:
                claimName: paperless-ngx-media
            - name: backup
              persistentVolumeClaim:
                claimName: paperless-ngx-backup
