apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data://c3mz4/Gr6F99Z0OYz1nLj3yULflH7hSuLI6BXMHmi//gD8orIgvOKc8JX+3KVekilXizLyh6CfXMvIji4EMa+s+wKlgA6eZtFPv5rvw4clSCNClb0=,iv:mUz6O7gzwFagioSsWOJvqrv+B8x1YFoRtjP/7dkvLBA=,tag:A1BjL+87X/lLhm19p0XUBA==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YUU0SkNoWjUrMFBqYWhE
        cHlsUitBWW9qZDhQNEIvZFlvQ3VDeEF4T2hBCnNXYWloSjFyYlRkY0h0MCtWeXRo
        YUhhNFp1VmhFMTdDNzRNdHYvQm96ZzAKLS0tIC92UW5IaENKdWJQUy85WFdxSDBN
        SU9HeG9yQUFhRCtHNlBiOHA2SjFHZUEK42kzero2i6SpX85OInPIf95ptixLi8md
        lGYUvO/KQUhQmuC3GDjUtQwF4XL8Jh0qX9D6Y6CPtyVi2g0zOetKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-25T12:16:42Z"
  mac: ENC[AES256_GCM,data:CvyjHa0c320GTHYDP1QgYwAVkOIhNqoAWzaFfpe/yWrAbroZoLvS+qX+tqd7+T1wrlV7BLoSYwA1m8aRovHG7q+dAp8zoHBlFAAqHFretJEDIP2S24LLrf3ak2WlGQXF+Gf/Gw5RqxLg0Ka79IVifbw3JadFB69YGUsxBD4kxfU=,iv:tzxO6ZtPBVlnmHUM4OCRntccp4OEwPUpZ/0/ZJfgV0E=,tag:zfEnw2vC0IcvXN3SR1oSLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
