apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
type: Opaque
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:CxIoxsI=,iv:7w80NXM45SdrPbdte4UdkGXRBv11D+0HtXzCvMOCAfQ=,tag:wExVUjB96x8oZhwgwSHVPQ==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:P4CvGeo=,iv:a33XIUa8WlRUjtmc3pnqQwzvCbB4VsSGmdj7W4N9dP0=,tag:2v5DEMi9QipLIHJsteSUhw==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data://c3mz4/Gr6F99Z0OYz1nLj3yULflH7hSuLI6BXMHmi//gD8orIgvOKc8JX+3KVekilXizLyh6CfXMvIji4EMa+s+wKlgA6eZtFPv5rvw4clSCNClb0=,iv:mUz6O7gzwFagioSsWOJvqrv+B8x1YFoRtjP/7dkvLBA=,tag:A1BjL+87X/lLhm19p0XUBA==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YUU0SkNoWjUrMFBqYWhE
        cHlsUitBWW9qZDhQNEIvZFlvQ3VDeEF4T2hBCnNXYWloSjFyYlRkY0h0MCtWeXRo
        YUhhNFp1VmhFMTdDNzRNdHYvQm96ZzAKLS0tIC92UW5IaENKdWJQUy85WFdxSDBN
        SU9HeG9yQUFhRCtHNlBiOHA2SjFHZUEK42kzero2i6SpX85OInPIf95ptixLi8md
        lGYUvO/KQUhQmuC3GDjUtQwF4XL8Jh0qX9D6Y6CPtyVi2g0zOetKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-27T14:09:19Z"
  mac: ENC[AES256_GCM,data:Fphkah3baZehJRbS8tbnLIKccgd2YAlGQRmSx8dIa0gsKQD4I34CyBs6M//MbPgdl8aL/rCjhPYj2u4QzLcBs4ymbtiVqxVAh374c5G2vgnIN+hY5DzXcUc34xPY9kh1rz5h8fJRp7fCDBdUxdF58jsbFnRa086m0hyyRMyCbow=,iv:/80VOzgU5OLZO6G46ESXBubZbx0fJkAatFetScgNhhs=,tag:lsOh0eLpavfuVQu64565tw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
