apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: volsync
  namespace: volsync-system
spec:
  url: https://backube.github.io/helm-charts
  interval: 6h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync-system
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: volsync
        namespace: volsync-system
      interval: 6h
