apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:vtbMJOA=,iv:x0PZhlzy60cGxxQaud0JwRb8Yx1UfX01o78PetAmVSU=,tag:6Nu26wk7NEMe+3HcV4Xbew==,type:str]
  admin-password: ENC[AES256_GCM,data:9L0j7m0=,iv:OfPVhLuZkhnqJqJReYxiyxn5ncK6mIw3QVGub5utS3o=,tag:i8mJ5uK4wv7W+BVtx8KCPA==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR2QxZllaUDFxUGkya25E
        TmY0cTFrM0t4T3BuVjhnSXhvWnMrdVdTV1VvCkhwSDZseUk2eHBma0xRTU5zMVZD
        TUhaTFBTd0FReTk2cmROaUlaNDd6R1EKLS0tIEFyWCtnRXRNT1hVOU5MZ3QzcWox
        ZnpWZmF0clpiQWpIQW40bEZpZUQxQUUKqNjX0tBqJNktOl41QddZdopHrqbYBfhe
        uKETtGRw6rYW3ioaRRtr2CMQ+a4fGFvJIuAkzbcG/fJS/pmUtxVsEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T17:23:26Z"
  mac: ENC[AES256_GCM,data:tVuDgmEPdPupeh9eUM8J3C9oGiQ6rTK15bvrfH8cM4+qcL0zHbSrhGcGrd7VqnlDSUyw+3DY3JCFRocjVGhDzHP9f30jrZaQyhL17H0lMQ2Qy4SqnnWH9gghIUfbeme+irNT/w5+jZLQHvRJhYNjm69iw2r7XOUwwBEhGIncjEk=,iv:nrfOBpskYNZhtD3a8lkc+tOTxiDyMrW1OkMjSYqsGJI=,tag:BkoPaj1Xv/VVh/AjuSuosA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
