apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: networking
  labels:
    app: blocky
data:
  config.yml: ENC[AES256_GCM,data:nuS3oN0Dzy/L/qx6pliJlc9vyti4cj8XWq2ke6GJHNigkRzuDBPepT4jjyO0sj8sKo8nmQrOQFxAHyVoIsNfghzXDwc3c28xGsL98KC98zSDo9vL3AXiMyrBtCtZW4rg1bn0LKdVqLeJmaVNQwhgdMSH8/4E2jysxLv4jcs8l0pm1tdq61cjLgHIC4EPC4ln/OCGpRIpqJSV8OD74teyLdEbcCFueu7vXV7M4NYOUarkeD+QxnTgl18n/8qmVdWxbJESioTD1LF3UECFhxdVpw87scNS5C/9ZTSgWsnRgWeNw528CGBuk9iE3P9nxlWP5gftzFIsB/h1Rj+r2x2J2uEogX8hXjcrGubDIH2djNaOPwKapr55fHGabr5E3Q2lvtbgHkI8aec9F8zRQ7iDuczdNxOrdyQbVjyBrrvjlQ1fFc5Hbz+srEzWCM8S8a81fjy8ttfkQXT0fEG2GcEjXhCA6ygq2roAV/AB0qPdPtq0s/4gq7ydY1/P37H4ZsqzljytUI7nNJP3WXccJ1Soy3rd5izIXdgFfdwSwUUBes8pP7esZFgS14fqrp/J0z7x6LlXXSxwHPZcgV5X4d9I/7Jk2rhuIu6OhYnmdGh/+BjayxPdR9g3+s/4RFtfDtIwL2DWNmDrJvSJ40cLSaC0/358koi2fRfRl/WoCSinh/Ip63aW7ZRipVdif7515hA8N5K3ajHJIFelWCcAm7YYJxPkctARt44lc0c4gM+HIu1KUaxSpgm1eg+kN/ZIgPe0/HDjajXFqicO1LMmgQ68rwHy/lGK+k/llYcmVRObP9pQ78XKLP6rrKX/QKsedjThKM+eJ9HxH+KuO0vAgPL2O0nnot70JQaX44H4snmNF/MDCaB0y/ODh880sB4MPdXDOf4/RYd+aAUvCaas/qinimvZv0394yFUfRKeTG6kpBe0zWVrHG3v/i4ekZWVlaETEAX1zgM43KgoTuvhpeeQIiv7q10L5abTghNI1ZvAB5CfxobJfYB2wpulsZmwpwwYce1rBt0b/q4X8piPDyTX9LLq3vNcTw5e2NwjCVEHOwfyZFJIlMC8qdAG5a3iFY0zKtw3/k6a83ucmJEhJVCwWMhS/iSEv4NKknL6QpJzsEOhik5N94+Rw2UIx6/cCSUFY/ANFKjgoparlptaDAlaoSqZtWg1PnJi23B6aSmqi30rbEjPcEa/cle0DKff0C668EN2FPJ1JcGzkYuzifjZrwLokh6PkHeBlEbLrhQ1xAS4Lc9AHFD296EZ8RwHQMDhujrutRv2tA34yTF2ZNIF8/F1KdAZe3CC/MlUJ5f4WlTb0uui07ibRymTWWw27Tgv1KqM8/jVRz2Fc+lJc3b4llEwpmx+0rudk5yW/U77HRQhw+5oa9RayRMORv1SACokDzdiKBuQW8HR3JybgpgHW50WTNemwRWYzxKo4e0A7w3uYSbN/R6CdHMuRghRHtboDhIcY8Qs7omqJuC3QxF8rskYZcMCUEKAsCNQk4MCz7jHYgZGjEw9eM0y5QHwT7ULreT/T6XYWIxRGtk43aj9F8c8cKLuAXoWPZDmU4tGJb1qmX34LGaI7mT2hbLOsairRpOK6jcHoO474aait0Qct+8JhXycjskFL3/xzo4O/ypWwSXwxlxIDJejcKoCS2rV8+1yB5JGLddqdibX8yNe87HEaiJ40Wz/Hj8xLPGa72CC3Z2OBi40jqcE80en3YNYWetFMvfJJlRa+lsUS7I49n8X8Xr46oaAaf62e+pbOB/xnTC775vuQFFzAaih2uQ0DcvJ7UOeIw==,iv:C3xP+j8LXanmtBxZvgW/zHQAZq9Nnrg2VjLwBdjvIAY=,tag:+YX2phA3UZDL/6GH+iIeWQ==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY2x1cGRiclRMZFRQQlVZ
        TURPSVpqQ2lLRnJXenNtRHpWMHJrVGJYQUUwCnZxaDh0ODIrZkZjekVYQ2lod3lU
        bGFTU0FvVmhEYWRBVzBCOU83RHFteFUKLS0tIFBMTXdpVmhsSU9jMG1LcXhybTRO
        RUdJdUFZMHUrWHNqYldkNWRRSmFYaEkKRmAp5D55F6zc+euf+35j5Ugwb1gCBiOQ
        zlcIqTdnGw1rbH3eqHFwKf67WwSC03e6avQpwjectOa9G5M5CyTloQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T12:52:32Z"
  mac: ENC[AES256_GCM,data:Ldq8mfvDh8GRQfvS7JqzzSVT4FNeOB8iTINtXYFGI77KJjXEtVwcHqdJJpnjScvLldicncZunypp/9RxNniqQ0nvdQ0HI/a5jMOFtmxAiAuYpns1QNqSgPh9UvhY+ahOHy9dQikTnVFLfaj9gw0aeL8GKpTDGqcs4I0HgoT/UzA=,iv:7rJgHV/UJVMk9mPVD1E1jaNrhjmTQ/Eo8oaaC0v/4m8=,tag:I9keCv/1y2G8jJEkl1a3og==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
