apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: networking
  labels:
    app: blocky
data:
  config.yml: ENC[AES256_GCM,data:4XIZ/WWtXVGC0wkCY0eYamntOhcJJbrduQTlHX3ocUz7eV7BQ11zj++XjlL1PwzPKFBcl9vFiviwawhFh5i69zLIQYx90UA2ME7K7EH7FHwRgCVvpAVBRazA/UC7pUlkU5EkO3dSgWImo0aPDmMHDPW0ApwwmFWbY6eTO/rkoJnWSbStrcUtSDiS1XyDa4LVQhWP8OfgXFmojTMIhzXg/ue5DXayYGrS/pwjtEezQKFg0RC388a7yXJSWuf/b/oByxj2xVO0tMRkBcEIz4MXCjXCZuxc9MZPSixjn79DXyUZjXRtbq6C5VB4qHmF33AHIk4wqBKoRSxR0uKvqsC05vVCTiRg3ghmBcc9M+LeXqkW1z16eA2gUUQuO9AmkFawjEbW7jalxKUWIX7vW1fwAGV7Lq3/sLp4dypLM0plpW8yRaL/MnjxcZSYojcBAND3hBgKiYFOZsvzQWdkDpQEZ3bfCoIo88qVxHuKbue3qBdf4dy4JgbkzJylYN3YTm/KM03eUSxqVQ6I3+DA0dNG1VOgGW0bj986oI6B5Ms+/nd/TAsjZCB2sDU0WM8O8o0Cu7cyvBDv4AF89omsxmt/5f9N15ZIDhwCFgMSUWuYl2A3Gm/guCt9MFYFqG8G6JPxbtF4xwsqFxumEJV9WFgiPWIyipT/3sHC45vOuJLf9Tt57elWQZOjVlQqRwdJIT8PzHNJt78maAnMYMVyL8UFxCAMvpRk7K3ggGLR8+z010j7G5Z9lq+lWtAGj8vUWGuq/0lDydKpgXW8n0aQJmCuf10V5mAHzWZyKWcn61F2GCp5FxwqHAahzBjNjVpQ/mqnIvtW9qltSplvOODfaefW6dSdlBohZgSS+iIA0K5X/xw059yGRHrZ2IjZ9rl4MrGRI8t66mqO5dV/wjjTKeFKUh1DzA2az2TQsN76W0pFVKjmwCpbRUgBblAikj6SEtAx//hm+NJ6amKaMoooggRlJbjoJMvweXWl3LxwsYzFsvVfTddx4EuhcMfqf494pYQ0hMeuxI2lXWc8Tya9qs0FYMNQDruZ+ECUxcRKPyUyDkYyqwrHhi7M+HkbATbTucvKXtjog412nDlGccJJY+whF962OWq40hYMPUQZLZzj8E/RnptZFDbQQycl18q1EoSFQrQJsA8Ex3Hv2Lw7gpK6EUIEgo46vZpd2MQ5NYR/rSSS58FCadYFpS1otIp02Pag2rW6fG63cWJjWdoIj04zKcWTmlDnfmx3xZ6hvSM/0fSViYtvSJg2lpxZOf4vtv4AwLaNOLj4n9AvqWpTUsv/3Ug8pWUpZebiTPZGGilZ/31/CDzAxP1Cvy4anMRhi+eGgIXQGxuO50vy/sOUjpVxWrhCdnbmPz7jokJkOgn5ya7ESsgK7+b8oQa4R/M+de5dgRQM6r9A0/gmgv3NfcwUgv+WrJ5mlRTUHxqkSvL2GnpdAIX5HRlJCh3fNuUUMaLnrQgNcVonHJZv2Gd3xeBJTLvw6uveipT14Ruo2ym1xAu98+TQu1NNJbQsCCJBAdWFAiNoHh142+hsNVp1bLBlTT2QBLfv5pD169GR8a9lTKagRnopeOWa3npTpNSUn9lAFwOWBpMUQp12cUzbhTH3GbHjTNyYNNSd/RNm2AI2IfRT8tlJoduEzlIqawpngB/HyVL/ryzcoMEVxmM3o1ro2zTYtC+IAlXll+8DHO4TIKbCsDgj4YzeyhWuROYibxtmdyr07A6vNqaBO2wbGWekHj4GDL+Z1mzEGVZkN1/zeKE/NPuKKYXK4J8QXX+SirQw,iv:h/QTLbMX1BO5/oKMQaIoqf5BJEzAVheazMHxOvCxWR8=,tag:D+URqItb5Y9WogK6U+IYpg==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY2x1cGRiclRMZFRQQlVZ
        TURPSVpqQ2lLRnJXenNtRHpWMHJrVGJYQUUwCnZxaDh0ODIrZkZjekVYQ2lod3lU
        bGFTU0FvVmhEYWRBVzBCOU83RHFteFUKLS0tIFBMTXdpVmhsSU9jMG1LcXhybTRO
        RUdJdUFZMHUrWHNqYldkNWRRSmFYaEkKRmAp5D55F6zc+euf+35j5Ugwb1gCBiOQ
        zlcIqTdnGw1rbH3eqHFwKf67WwSC03e6avQpwjectOa9G5M5CyTloQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T20:22:04Z"
  mac: ENC[AES256_GCM,data:6UGNZSJiK/6DYf235pnOSPZZ6mYddLF6Ds7gdlViPomGj/TVs7G53KbHPrUCRawGYt+pNiLYDc9+e+Q2Hes7JKth8p7LRc39tm1KWuNEK+TjiJCMSEfPJt3rlr/lrGfInhu5mwKGH1J7QjYXMHZ4Y4CxO2Bc5ervAPTPD15GhO8=,iv:cJnjOgT+1lSUb/N6fhstNHEK8B4UassyPxVt48dNBQg=,tag:QP0KFB3JEw44109bmJ4wwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
